export const UPDATE_SQUARES = 'UPDATE_SQUARES';
export type UPDATE_SQUARES = typeof UPDATE_SQUARES;

export const GENERATE_TILESBAG = 'GENERATE_TILESBAG';
export type GENERATE_TILESBAG = typeof GENERATE_TILESBAG;